export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FINISHED = 'LOAD_USERS_FINISHED';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const SET_USER = 'SET_USER';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_FINISHED = 'SAVE_USER_FINISHED';
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';


export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FINISHED = 'DELETE_USER_FINISHED';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const LOAD_IMAGES = 'LOAD_IMAGES';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const LOAD_IMAGES_FINISHED = 'LOAD_IMAGES_FINISHED';
export const LOAD_IMAGES_ERROR = 'LOAD_IMAGES_ERROR';


export const ADD_TAG = 'ADD_TAG';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FINISHED = 'ADD_TAG_FINISHED';
export const MATCH_TAG = 'MATCH_TAG';

export const DELETE_TAG = 'DELETE_TAG';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FINISHED = 'DELETE_TAG_FINISHED';