export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FINISHED = 'LOAD_USERS_FINISHED';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FINISHED = 'DELETE_USER_FINISHED';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';